name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    #- uses: actions/upload-artifact@v2
    #  if: always()
    #  with:
    #    name: playwright-report
    #    path: playwright-report/
    #    retention-days: 30
    - name: Get Xray Cloud API token
      env:
        CLIENT_ID: ${{ secrets.client_id }}  
        CLIENT_SECRET: ${{ secrets.client_secret }}
      id: xray-token
      run: |
        echo ::set-output name=XRAY_TOKEN::$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$CLIENT_ID\",\"client_secret\": \"$CLIENT_SECRET\" }" https://xray.cloud.getxray.app/api/v2/authenticate| tr -d '"')
    #- name: Submit results to Xray-1
    # run: 'curl -H "Content-Type: text/xml" -H "Authorization: Bearer ${{ steps.xray-token.outputs.XRAY_TOKEN }}" --data @"xray-report.xml" "https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=QPI&testExecKey=QPI-246"'
    - name: Submit Multipart Test results to Xray-2
      run: 'curl -H "Content-Type: multipart/form-data" -X POST -F info=@testExec.json -F results=@xray_report.xml -F testInfo=@test.json -H "Authorization: Bearer ${{ steps.xray-token.outputs.XRAY_TOKEN }}" https://xray.cloud.getxray.app/api/v1/import/execution/junit/multipart'
    
